-- Update the callback URL to use localhost for development, or configure manually in production
-- UPDATE app_config 
-- SET value = '{"url": "http://localhost:5173"}'::jsonb 
-- WHERE key = 'live_callback_url';