-- Update product brands to 'Lattafa Perfumes' for all matching products
-- This migration updates the brand field for 150+ Lattafa products

UPDATE public.products
SET brand = 'Lattafa Perfumes',
    updated_at = now()
WHERE name IN (
  'Sehr Lattafa',
  'EMEER',
  'VICTORIA',
  'PETRA',
  'Afeef',
  'Khamrah dukhan',
  'KHAMRAH QAHWA',
  'Maahir Gold',
  '25ml 4 In 1 YARA GIFTSET',
  'THE KINGDOM WOMAN',
  'Bade Al oud amethyst',
  'Mahir black',
  'Haya',
  'Sakeena',
  'EMAAN',
  'BADEE AL OUD SUBLIME',
  'Badee Al Oud lattafa',
  'Angham',
  'Yara pink lattafa',
  'Yara Candy',
  'Yara moi lattafa',
  'Yara Tous lattafa',
  'Ajwad',
  'Liam blue shine',
  'Asad zanzibar',
  'RAED blur LATTAFA',
  'Raed Oud',
  'AJWAD pink to pink',
  'Fakhar Lattafa Silver',
  'Fakhar Lattafa Extrait',
  'Fakhar Lattafa Femme( Gold)',
  'Mayar lattafa',
  'HABIK FOR MEN',
  'HABIK FOR WOMEN',
  'Al noble ameer',
  'Hayaatim',
  'Qaa''ed Lattafa',
  'SUTOOR',
  'Velvet Rose',
  'Mohra',
  'Ajayeb Dubai',
  'Ajayeb Dubai portrait',
  'Hayatti',
  'Musk mood',
  'OUD MOOD ELIXIR',
  'Oud Mood Reminiscince',
  'Ana abiyedh poudree',
  'Ana Abiyedh coral',
  'Ana Abiyedh Leather',
  'Ana Abiyedh',
  'Rouat Al Oud',
  'Rouat Al musk lattafa',
  'Opulent musk',
  'Suqraat Lattafa',
  '20ml Yara moi oil',
  '20ml Yara tous oil',
  '20ml Yara candy oil',
  '20ml Yara oil',
  'Khaltaat Al Arabia - Royal Blends',
  'Ramz silver',
  'Hayaati Al Maleki',
  'LAIL MALEKI',
  'Victorioso Legacy',
  'Ejaazi',
  'Qaed Al Fursan untamed',
  'Qaed Al Fursan',
  'Qaed Al Fursan Unlimited',
  'TAMIMA',
  'ATLAST Lattafa',
  '150ML YARA TOUS ALL OVER SPRAY',
  '150ML ANA ABIYEDH ROUGE ALL OVER SPRAY',
  '150ML AMEERAT AL ARAB PRICE',
  '150ML ECLAIR ALL OVER SPRAY',
  '150ML AMEERAT AL ARAB ALL OVER SPRAY',
  '150ML MAYAR NATURAL INTENSE',
  'LAIL MALEKI 30ml',
  'LATTAFA 200ML BODY SPRAY (Carton)',
  'Badee Al Oud Amethyst',
  'Badee Al oud Honour And Glory',
  'Opulent Oud',
  'Velvet Oud',
  'Velvet oud lattafa',
  'Mayar cherry intense',
  'Mayer Cherry Intense',
  'Mayar natural intense',
  'Mayer Natural Intense',
  'KHAMRAH',
  'Najdia w/deo (Standard)',
  'Najdia w/deo 30ml',
  'Najdia intense',
  'Hayaati Florence',
  'Hayatti Gold elixir',
  'Hayatti Al Maleki',
  'Gift set Asad 5th anniversary edt.',
  'Gift set Asad 5th anniversary',
  'Her confession',
  'His confession',
  'THE KINGDOM MAN',
  'The kingdom woman',
  'Eclaire lattafa',
  'Musamam',
  'LIAM GREY',
  'ASAD LATTAFA',
  'Asad Zanzibar',
  'AL NASHAMA CAPRICE PERFUME',
  'AL Noble Wazeer',
  'Ajayeb dubai portrait',
  'RAMZ GOLD',
  'ANA ABIYEDH ROUGE',
  'ANA ABIYEDH ( WHITE )',
  'Ana Abiyedh 30ml',
  'Maahir Gold',
  'MAAHIR LEGACY',
  'MASHRABYA',
  'Qimmah Woman',
  'Velvet Musk',
  'Aura',
  'OPULENT DUBAI',
  'Raghav W/deo',
  'ARTISAN ETHNIQUE',
  'MAZAAJI',
  'Nasmaat',
  'AMEER AL OUDH INTENSE OUD',
  'TERIQ Lattafa',
  'OUD MOOD',
  '150ML HAYA',
  'MAYAR ALL OVER SPRAY'
);

-- Log the number of products updated
DO $$
DECLARE
  updated_count INTEGER;
BEGIN
  GET DIAGNOSTICS updated_count = ROW_COUNT;
  RAISE NOTICE 'Updated % products with brand "Lattafa Perfumes"', updated_count;
END $$;
