// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://snzjtphagdqnyxexlejd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNuemp0cGhhZ2Rxbnl4ZXhsZWpkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjAyMzUyNzksImV4cCI6MjA3NTgxMTI3OX0.EQurINkVFc36pEEBKoNTGr7-M8T1HDwLDlWh2m0Jp8o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});